name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Executable jarfile with Maven
      run: mvn -B assembly:assembly --file pom.xml
    - uses: actions/upload-artifact@v1
      with:
        name: techanalysisj-artifact
        path: target/techanalysis-0.0.1-SNAPSHOT.jar
    - name: Testcases
      run: mvn -B test --file pom.xml -Dtest=se.avelon.edge.formulas.FormulasTestcase

